# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: wuyaxv's pit.
footer_title: Contact Me
description: > # this means to ignore newlines until "baseurl:"
  <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://XXXLINKSTOWORK/XXXX">The articles on this website</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://XXXMYPERSONALWEBSITE/XXXXX">wuyaxu</a> is licensed under <a href="http://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY-SA 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1"></a></p>
#repository: https://github.com/wemake-services/jekyll-theme-hackcss
baseurl:   # the subpath of your site, e.g. /blog
url: http://192.168.100.10  # the base hostname & protocol for your site, change the {IP} to yours

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: 👋 
email: wuyaxu.info@gmail.com

navigation:
  - text: About
    url: /
  - text: Blogs
    url: /blogs

projects:
  # Template for ref.
  #  - name: git-secret
  #    description: A bash-tool to store your private data inside a git repository.
  #    link: https://sobolevn.github.io/git-secret
  #    image: https://github.com/sobolevn/git-secret/blob/7c9ae0b1853d4c15549027524121b9e40219fe47/images/git-secret-sm.png?raw=true

social:
  - service: github
    username: wuyaxv
    link: https://github.com/wuyaxv
  - service: x
    username: wu_yaxu
    link: https://twitter.com/wu_yaxu
  - service: telegram
    username: wuyaxv
    link: https://t.me/wuyaxv

# Plugins
plugins:
  - jekyll-seo-tag
